sudo: required
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - docker
before_install:
  - docker build -t pankajmalhan/react-docker -f Dev.Dockerfile .
script:
  - docker run pankajmalhan/react-docker npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "${access_key_id}"
  secret_access_key:
    secure: "${secret_access_key}"
  region: "ap-south-1"  
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-806107407018"
  on:
    branch: master
