version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  webtest:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"] 

